name: Build Web

on:
  push:
    branches: [ main ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: WebGL Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Library Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library

      - name: Build WebGL
        uses: webbertakken/unity-builder@v1.1
        with:
          unityVersion: 2019.4.4f1
          targetPlatform: WebGL

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          TARGET_FOLDER: .
          CLEAN: true
