name: Build Web

on:
  push:
    branches: [ main ]

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    

jobs:
  build:
    name: WebGL Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Library Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-2020.1.8f1

      - name: Build WebGL
        uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: 2020.1.8f1
          targetPlatform: WebGL

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
          CLEAN_EXCLUDE: '["index.html"]'
