name: Build Web

on:
  push:
    branches: [ main ]

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    

jobs:
  build:
    name: WebGL Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Heroku Login
        env:
          HEROKU_USER_NAME: "${{ secrets.HEROKU_USER_NAME }}"
        run: bash -c 'echo ${{ secrets.HEROKU_API_TOKEN }} | docker login -u $HEROKU_USER_NAME --password-stdin registry.heroku.com'
      
      - name: Build API
        run: docker build . --tag boundfoxstudios/computermuseum-api:$GITHUB_RUN_NUMBER
        working-directory: Backend/BoundfoxStudios.Computermuseum.WebApi
      
      - name: Push images
        run: |
          docker tag boundfoxstudios/computermuseum-api:$GITHUB_RUN_NUMBER registry.heroku.com/computermuseum-api/web
          docker push registry.heroku.com/computermuseum-web/web
      
      - name: Release images
        env:
          HEROKU_API_KEY: "${{ secrets.HEROKU_API_TOKEN }}"
        run: |
          heroku container:login
          heroku container:release -a computermuseum-api web  
      
      - name: Library Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-2020.1.8f1

      - name: Build WebGL
        uses: webbertakken/unity-builder@v1.2
        with:
          unityVersion: 2020.1.8f1
          targetPlatform: WebGL

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
          CLEAN_EXCLUDE: '["/index.html"]'
